// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// PLACEHOLDER FILE.
///
/// This file MUST be regenerated for your own Firebase project before
/// running the app. From the project root, run:
///
///   dart pub global activate flutterfire_cli
///   flutterfire configure
///
/// That command creates your Firebase project's real `firebase_options.dart`
/// (and the native `google-services.json` / `GoogleService-Info.plist`
/// files) automatically. See README.md for the full walkthrough.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'run `flutterfire configure` to add it.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlj6cJgcUTQ1B3v0GVNpUO7YiFcKYzb98',
    appId: '1:895793752440:web:d77ed258e338ee93b6408d',
    messagingSenderId: '895793752440',
    projectId: 'maxillo-6d285',
    authDomain: 'maxillo-6d285.firebaseapp.com',
    databaseURL: 'https://maxillo-6d285-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'maxillo-6d285.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABsknFynaBHq6uAulJqPftmL_ZpzRs2xU',
    appId: '1:895793752440:android:104a2829675e83a6b6408d',
    messagingSenderId: '895793752440',
    projectId: 'maxillo-6d285',
    databaseURL: 'https://maxillo-6d285-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'maxillo-6d285.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkkcMLJBby-SxEeGnO88T1kyWJnsZoKIQ',
    appId: '1:895793752440:ios:0a1ce07e899ad889b6408d',
    messagingSenderId: '895793752440',
    projectId: 'maxillo-6d285',
    databaseURL: 'https://maxillo-6d285-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'maxillo-6d285.firebasestorage.app',
    iosClientId: '895793752440-un2f3pc9d7scjuavpqgoojsngo95aqjo.apps.googleusercontent.com',
    iosBundleId: 'com.maxillo.com',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_MACOS_API_KEY',
    appId: 'REPLACE_WITH_YOUR_MACOS_APP_ID',
    messagingSenderId: 'REPLACE_WITH_YOUR_SENDER_ID',
    projectId: 'REPLACE_WITH_YOUR_PROJECT_ID',
    storageBucket: 'REPLACE_WITH_YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.maxilloai.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_WEB_API_KEY',
    appId: 'REPLACE_WITH_YOUR_WEB_APP_ID',
    messagingSenderId: 'REPLACE_WITH_YOUR_SENDER_ID',
    projectId: 'REPLACE_WITH_YOUR_PROJECT_ID',
    storageBucket: 'REPLACE_WITH_YOUR_PROJECT_ID.appspot.com',
  );
}
